### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by IRivera90** [team-grilled-cheese/back-end#14]
Add README file text for back end. 
Be sure to include table with authentication routes 

Verb | URI Pattern | Controller#Action
POST | /sign-up | users#signup
POST | /sign-in | users#signin
PATCH | /change-password/ | users#changepw
DELETE | /sign-out/ | users#signout

**Comment by Kayla-SA-W** [comment]
update read me with resources / documentation that we found

**Comment by ssolmonson** [comment]
Updated READ.ME to have similar matching links and documentation
